### ISSUE TITLE
Use "with" to open files

### ISSUE THREAD

**Issue by switchtrue** [marshl/SvnChart#1]
In Python you can use the following syntax to open a file and have a reference to it. This is preferred over plain old `file.open` as it will automatically close the file if exceptions occur.

https://docs.python.org/2/tutorial/inputoutput.html#methods-of-file-objects

``` python
with open('workfile', 'r') as f:
    read_data = f.read()
```

**Comment by marshl** [comment]
Fixed (I wish more languages had this construct, the only other I know of is using() in C#)

**Comment by switchtrue** [comment]
When you commit, you can reference an issues with the syntax #<issue-number>. For example #2. This not only makes the issue number a link in the commit message but it will also automagically add a message with a link to a commit. Check out [this](https://github.com/Fivium/ScriptRunner/issues/7) for an example.

You can also close issues - see here: https://help.github.com/articles/closing-issues-via-commit-messages/
