### ISSUE TITLE
Use PEP8 formatting

### ISSUE THREAD

**Issue by switchtrue** [marshl/SvnChart#2]
~~All~~ Most popular Python code conforms to the PEP8 style guide (link below). If you also use this same guide, it has the advantage that when looking at other peoples code it looks instantly familiar and more readable to you because this is how you are used to writing your code. Plus it makes you code better for the community. I highly recommend following this, notable things you would want to change are:
- [Limit all lines to a maximum of 79 characters.](https://www.python.org/dev/peps/pep-0008/#maximum-line-length)
- [Function names should be lowercase, with words separated by underscores as necessary](https://www.python.org/dev/peps/pep-0008/#function-names)
- [Class names should normally use the CapWords convention](https://www.python.org/dev/peps/pep-0008/#class-names)
- [Avoid extraneous whitespace in the following situations](https://www.python.org/dev/peps/pep-0008/#pet-peeves):
  
  ```
  Immediately inside parentheses, brackets or braces.
  
  Yes: spam(ham[1], {eggs: 2})
  No:  spam( ham[ 1 ], { eggs: 2 } )
  ```

https://www.python.org/dev/peps/pep-0008/

**Comment by marshl** [comment]
PEP8 compliance fixed, still have to fix function and class names

**Comment by marshl** [comment]
All fixed
