### ISSUE TITLE
Better method of constructing user_commit_count

### ISSUE THREAD

**Issue by switchtrue** [marshl/SvnChart#3]
You have a comment [here](https://github.com/marshl/SvnChart/blob/master/SvnChart.py#L103) that says:

> there has to be a better way to do this

Not 100% sure what you are referring to whether the loop or the adding to the dictionary, but there are a couple of options you can do

The adding to the dict and the if statement can be done in a one-liner using the [.get()](https://docs.python.org/2/library/stdtypes.html#dict.get) function on the dict type like this.

``` python
for entry in log_entries:
    user_commit_count = user_commit_count.get(entry.author, 0)
```

Alternatively, and probably the "pythonic" way, you can do this which is the whole thing in one line:

``` python
user_commit_count = dict(zip([x.author for x in log_entries], [0]*len(log_entries)))
```

In this, [zip()](https://docs.python.org/2/library/functions.html#zip) takes two or more arguments that are lists of the same lengths and returns a new, single list of tuples where the nth element of each list is in the tuple together. The `[x.author for x in log_entries]` is using Pythons list comprehension (which is awesome by the way) and generates a new list by iterating over the log_entries and returning the value of the expression to the left of the `for`.Finally, `[0]*len(log_entries)` is creating a list of zeroes with a length of the number of items in log_entires.

Alternatively to the above you can use [map()](https://docs.python.org/2/library/functions.html#map) and a lambda expression. `map()` is running the lambda expression in argument 1 for each of the items in the list in argument two and returning the results of this as a new list. I personally prefer the list comprehension. 

``` python
user_commit_count = dict(zip(map(lambda x: x.author, log_entries), [0]*len(log_entries)))
```

**Comment by marshl** [comment]
Fixed
